### ISSUE TITLE
Já tens o script a funcionar?

### ISSUE THREAD

**Issue by Maslor** [TonyFreire/chat-facebook-terminal#1]
Estava aqui a ver se o experimentava mas não está a correr com o node:

<img width="726" alt="screen shot 2016-02-18 at 08 41 22" src="https://cloud.githubusercontent.com/assets/9674408/13137830/6d4ec4f6-d61b-11e5-85f9-11381026ccaf.png">

**Comment by Maslor** [comment]
Esqueci-me de fazer download de algum modulo?

**Comment by TonyFreire** [comment]
sim tens de fazer npm install

**Comment by Maslor** [comment]
ah okok. Do colors?

**Comment by TonyFreire** [comment]
nao os modulos estao todos no package,json . é so fazeres npm install

**Comment by TonyFreire** [comment]
ainda falta me fazer um readme a explicar! e precisas de apagar uma linha no node_modules pq tem la um print chato

**Comment by Maslor** [comment]
Ahh ok!
